/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List contributions
         * @description The append-only ledger, newest first, with gift titles.
         */
        get: operations["admin-list-contributions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contributions/{contribution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Confirm or cancel a contribution
         * @description Only the admin transitions contribution status. Confirming stamps confirmed_at.
         */
        patch: operations["admin-moderate-contribution"];
        trace?: never;
    };
    "/api/v1/admin/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all gifts
         * @description Every gift with computed progress, including deactivated ones.
         */
        get: operations["admin-list-gifts"];
        put?: never;
        /** Create a gift */
        post: operations["admin-create-gift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/gifts/{gift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a gift */
        put: operations["admin-update-gift"];
        post?: never;
        /**
         * Delete or deactivate a gift
         * @description Hard-deletes only gifts with zero contributions; otherwise deactivates (the ledger is append-only history).
         */
        delete: operations["admin-delete-gift"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Guest dashboard
         * @description Every group with per-guest RSVP state, plus headcounts by category.
         */
        get: operations["admin-guest-dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/guests/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export guest list as CSV
         * @description PT-BR headers and values (grupo, nome, principal, categoria, presenca).
         */
        get: operations["admin-export-guests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import the guest list
         * @description Uploads a CSV or XLSX export of the couple's spreadsheet (headers: nome, grupo, principal, categoria — case/accent-insensitive). Upserts identity fields only; RSVP answers are never touched. Homonyms across groups are reported as conflicts, never written.
         */
        post: operations["admin-import-guests"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List uploaded images */
        get: operations["admin-list-media"];
        put?: never;
        /**
         * Upload an image
         * @description Stores the image in the public bucket and records its CDN URL.
         */
        post: operations["admin-upload-media"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an image
         * @description Removes the object from the bucket and the record from the library. Sections still referencing the URL will show a broken image — update them first.
         */
        delete: operations["admin-delete-media"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List guestbook messages */
        get: operations["admin-list-messages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve or reject a message
         * @description Moderation exists so a future public guestbook wall is purely additive (AD-14).
         */
        patch: operations["admin-moderate-message"];
        trace?: never;
    };
    "/api/v1/admin/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all sections
         * @description Every section in render order, including disabled ones.
         */
        get: operations["admin-list-sections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sections/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update one section
         * @description Replaces the payload and visibility of one slug. The payload field must match the slug (e.g. body.hero for slug hero).
         */
        put: operations["admin-update-section"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get site content
         * @description Returns every enabled editorial section in render order — the single call the public site makes for all of its copy.
         */
        get: operations["get-content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List gifts
         * @description Active gifts with computed progress (declared + confirmed centavos, remaining units for quota gifts).
         */
        get: operations["list-gifts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gifts/{gift_id}/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Declare a contribution
         * @description The guest's "já fiz o PIX" commit point: records a declared contribution (admin confirms when the PIX lands) and returns the copia-e-cola again. Quota gifts are serialized under a row lock so the last quota cannot be double-claimed.
         */
        post: operations["declare-contribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gifts/{gift_id}/pix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview PIX code
         * @description Side-effect-free copia-e-cola preview — window-shopping creates nothing. The contribution is only recorded by POST /gifts/{gift_id}/contributions.
         */
        get: operations["preview-gift-pix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find your invitation
         * @description Exact normalized full-name match. Returns the guest group with every member's current RSVP state. No fuzzy matching or suggestions — misses return 404.
         */
        post: operations["lookup-guest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggest guest names
         * @description Prefix typeahead for the RSVP name field: up to 8 full names, accent- and case-insensitive, rate-limited, debounced client-side. Returns names only — group data still requires the exact lookup.
         */
        get: operations["suggest-guest-names"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guests/{group_id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit RSVP
         * @description Records one yes/no per member of the group. Idempotent: resubmitting overwrites earlier answers. Rejected after the RSVP deadline.
         */
        post: operations["submit-rsvp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Leave a message for the couple
         * @description Creates a pending guestbook message (Recado aos noivos). Publicly write-only: messages are read and moderated in the admin.
         */
        post: operations["create-message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Railway healthcheck endpoint: returns 200 when the service and its database connection are healthy.
         */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminGiftsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AdminGiftsOutputBody.json
             */
            readonly $schema?: string;
            gifts: components["schemas"]["GiftView"][] | null;
        };
        BigDayPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            programme?: components["schemas"]["ProgrammeItem"][] | null;
            /** @description Section heading shown on the site. */
            title: string;
            /** @description Venue guidance (outdoor, grass — advise footwear). */
            venue_notes?: string;
        };
        Conflict: {
            db_group?: string;
            file_group?: string;
            name: string;
            reason: string;
        };
        ContentOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContentOutputBody.json
             */
            readonly $schema?: string;
            sections: components["schemas"]["Section"][] | null;
        };
        ContributionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContributionInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Amount in centavos. Optional for quota gifts (defaults to one quota); required for free-amount gifts.
             */
            amount_centavos?: number;
            /** @example Eduardo Silva */
            contributor_name: string;
            /**
             * Format: uuid
             * @description Guest group, auto-filled by the site after lookup.
             */
            group_id?: string;
        };
        ContributionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContributionOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            amount_centavos: number;
            /** Format: uuid */
            contribution_id: string;
            /** Format: uuid */
            gift_id: string;
            pix_code: string;
            /** @enum {string} */
            status: "declared" | "confirmed" | "cancelled";
        };
        ContributionView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContributionView.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            amount_centavos: number;
            /** Format: date-time */
            confirmed_at?: string;
            /** Format: uuid */
            contribution_id: string;
            contributor_name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            gift_id: string;
            gift_title?: string;
            /** Format: uuid */
            group_id?: string;
            /** @enum {string} */
            status: "declared" | "confirmed" | "cancelled";
        };
        ContributionsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ContributionsOutputBody.json
             */
            readonly $schema?: string;
            contributions: components["schemas"]["ContributionView"][] | null;
        };
        DashboardOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DashboardOutputBody.json
             */
            readonly $schema?: string;
            groups: components["schemas"]["GroupDashboardView"][] | null;
            headcounts: components["schemas"]["HeadcountsView"];
        };
        DeleteGiftOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteGiftOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Gifts with contributions are never hard-deleted; they are deactivated.
             * @enum {string}
             */
            outcome: "deleted" | "deactivated";
        };
        DressCodePayload: {
            /**
             * @description Short dress-code formula.
             * @example Sofisticado, confortável, vestido longo, esporte fino.
             */
            attire?: string;
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GettingTherePayload: {
            /** @example Rua Piraju, 306 – Jardim Paulista, Atibaia – SP, 12947-321 */
            address: string;
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** Format: uri */
            map_embed_url?: string;
            parking_notes?: string;
            /** @description Section heading shown on the site. */
            title: string;
        };
        GiftParamsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GiftParamsBody.json
             */
            readonly $schema?: string;
            active: boolean;
            description?: string;
            /**
             * Format: uri
             * @description https URL of the couple's registry (link gifts only).
             */
            external_url?: string;
            /** Format: int64 */
            goal_centavos?: number;
            /** Format: uri */
            image_url?: string;
            /**
             * @description Defaults to pix on create; REQUIRED on update. pix: metas/cotas. link: external registry card (requires platform + https external_url, forbids money fields).
             * @enum {string}
             */
            kind?: "pix" | "link";
            /**
             * Format: int32
             * @description Requires quota_centavos.
             */
            max_units?: number;
            /**
             * @description Store slug, required for link gifts (mercadolivre, amazon, camicado, …); the SPAs map it to a logo badge.
             * @example mercadolivre
             */
            platform?: string;
            /** Format: int64 */
            quota_centavos?: number;
            /** Format: int32 */
            sort: number;
            title: string;
        };
        GiftView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GiftView.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Sum of admin-confirmed contributions. Always 0 for link gifts.
             */
            confirmed_centavos: number;
            /**
             * Format: int64
             * @description Sum of declared (not yet confirmed) contributions. Always 0 for link gifts.
             */
            declared_centavos: number;
            description?: string;
            /**
             * Format: uri
             * @description The couple's registry URL (link gifts only).
             */
            external_url?: string;
            /** Format: uuid */
            gift_id: string;
            /**
             * Format: int64
             * @description Goal amount in centavos (BRL). PIX gifts only.
             */
            goal_centavos?: number;
            /** Format: uri */
            image_url?: string;
            /**
             * @description pix: metas/cotas paid by PIX through the site. link: external store registry — the card redirects and no money flows through the API.
             * @enum {string}
             */
            kind: "pix" | "link";
            /**
             * Format: int32
             * @description Maximum sellable quota units; null means unlimited. PIX gifts only.
             */
            max_units?: number;
            /**
             * @description Store slug for link gifts; the SPAs map it to a local logo asset.
             * @example mercadolivre
             */
            platform?: string;
            /**
             * Format: int64
             * @description Fixed quota unit in centavos; contributions must be multiples. Null means free amount. PIX gifts only.
             */
            quota_centavos?: number;
            /** Format: int32 */
            sort: number;
            /** @example Para o João fazer a barba */
            title: string;
            /**
             * Format: int64
             * @description Remaining quota units (only for unit-limited PIX gifts). Optimistic: declared + confirmed consume units.
             */
            units_left?: number;
        };
        GiftsIntroPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        GiftsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GiftsOutputBody.json
             */
            readonly $schema?: string;
            gifts: components["schemas"]["GiftView"][] | null;
        };
        GoodPracticesPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            rules?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        GroupDashboardView: {
            /** Format: uuid */
            group_id: string;
            label: string;
            members: components["schemas"]["MemberView"][] | null;
        };
        GroupView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GroupView.json
             */
            readonly $schema?: string;
            /** Format: uuid */
            group_id: string;
            /** @example Eduardo e família */
            label: string;
            members: components["schemas"]["MemberView"][] | null;
        };
        HeadcountsView: {
            /** Format: int64 */
            no: number;
            /** Format: int64 */
            pending: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            yes: number;
            /** @description Confirmed guests per category (adult, child, baby, elderly, uncategorized). */
            yes_by_category: {
                [key: string]: number;
            };
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Overall service status.
             * @example ok
             */
            status: string;
        };
        HeroMilestone: {
            /**
             * Format: date
             * @description Optional date shown above the label.
             */
            date?: string;
            /**
             * Format: uri
             * @description Public CDN photo; the site shows brand art while empty.
             */
            image_url?: string;
            /**
             * @description Short caption under the arch.
             * @example O pedido
             */
            label: string;
        };
        HeroPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @example Atibaia – SP */
            city_label: string;
            /** @example Jade & João */
            couple_names: string;
            /**
             * Format: date-time
             * @description Ceremony start, ISO 8601 with America/Sao_Paulo offset.
             * @example 2027-08-07T15:00:00-03:00
             */
            event_datetime: string;
            /** Format: uri */
            hero_image_url?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Up to three story arches rendered beside the names. */
            milestones?: components["schemas"]["HeroMilestone"][] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        ImportOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ImportOutputBody.json
             */
            readonly $schema?: string;
            /** @description Guests created by this import. */
            added: string[] | null;
            /** @description Rows refused: homonyms across groups or duplicates in the file. */
            conflicts: components["schemas"]["Conflict"][] | null;
            /** @description Row-level parse issues (PT-BR). */
            errors: components["schemas"]["RowIssue"][] | null;
            /** @description Guests in the database that the file no longer mentions. Never deleted automatically. */
            unmatched: string[] | null;
            /** @description Existing guests whose identity fields were refreshed. */
            updated: string[] | null;
        };
        Lodging: {
            /** @example Centro */
            area?: string;
            /** Format: uri */
            link?: string;
            /** @example Pousada Jardim */
            name: string;
            notes?: string;
            /** @description Whether the wedding shuttle (translado) serves this lodging. */
            shuttle_served: boolean;
        };
        LookupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LookupInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Full name as written on the invitation. Matching is exact after normalization (case and accents ignored).
             * @example Eduardo Silva
             */
            full_name: string;
        };
        MediaListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MediaListOutputBody.json
             */
            readonly $schema?: string;
            media: components["schemas"]["MediaView"][] | null;
        };
        MediaView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MediaView.json
             */
            readonly $schema?: string;
            alt?: string;
            bucket_path: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            media_id: string;
            /**
             * Format: uri
             * @description CDN URL browsers load the image from; paste into section payloads.
             */
            public_url: string;
        };
        MemberView: {
            /** @enum {string} */
            attending: "pending" | "yes" | "no";
            /** @enum {string} */
            category?: "adult" | "child" | "baby" | "elderly";
            /** @example Eduardo Silva */
            full_name: string;
            /** Format: uuid */
            guest_id: string;
            /** @description Whether this guest is the group's primary contact. */
            is_primary: boolean;
        };
        MessageCreatedOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MessageCreatedOutputBody.json
             */
            readonly $schema?: string;
            /** Format: uuid */
            message_id: string;
            /**
             * @description New messages always start pending; the couple moderates them in the admin.
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected";
        };
        MessageInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MessageInputBody.json
             */
            readonly $schema?: string;
            /** @example Eduardo Silva */
            author_name: string;
            /** @example Felicidades aos noivos! */
            body: string;
            /**
             * Format: uuid
             * @description Guest group, auto-filled by the site after lookup.
             */
            group_id?: string;
        };
        MessageView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MessageView.json
             */
            readonly $schema?: string;
            author_name: string;
            body: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            group_id?: string;
            /** Format: uuid */
            message_id: string;
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
        };
        MessagesIntroPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        MessagesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MessagesOutputBody.json
             */
            readonly $schema?: string;
            messages: components["schemas"]["MessageView"][] | null;
        };
        ModerateContributionInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ModerateContributionInputBody.json
             */
            readonly $schema?: string;
            /**
             * @description confirmed: the PIX landed. cancelled: it never will.
             * @enum {string}
             */
            status: "confirmed" | "cancelled";
        };
        ModerateMessageInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ModerateMessageInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            status: "approved" | "rejected";
        };
        OurStoryPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        PixOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PixOutputBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            amount_centavos: number;
            /** Format: uuid */
            gift_id: string;
            /** @description Static PIX BR Code (copia-e-cola), CRC included. */
            pix_code: string;
        };
        ProgrammeItem: {
            /** @example Recepção dos convidados */
            label: string;
            /**
             * @description Local time (America/Sao_Paulo), HH:MM.
             * @example 15:00
             */
            time: string;
        };
        RSVPAnswer: {
            /** @enum {string} */
            attending: "yes" | "no";
            /** Format: uuid */
            guest_id: string;
        };
        RSVPInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RSVPInputBody.json
             */
            readonly $schema?: string;
            /** @description Exactly one answer per member of the group. */
            responses: components["schemas"]["RSVPAnswer"][] | null;
        };
        RSVPPayload: {
            /** @description Rich text as Markdown. */
            body?: string;
            /**
             * Format: date
             * @description Last day (inclusive, America/Sao_Paulo) to submit or change RSVPs. Enforced server-side.
             * @example 2027-07-07
             */
            deadline: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        RowIssue: {
            /** Format: int64 */
            line: number;
            message: string;
        };
        Section: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Section.json
             */
            readonly $schema?: string;
            big_day?: components["schemas"]["BigDayPayload"];
            dress_code?: components["schemas"]["DressCodePayload"];
            /** @description Disabled sections are hidden from the public site (server-side). */
            enabled: boolean;
            getting_there?: components["schemas"]["GettingTherePayload"];
            gifts_intro?: components["schemas"]["GiftsIntroPayload"];
            good_practices?: components["schemas"]["GoodPracticesPayload"];
            hero?: components["schemas"]["HeroPayload"];
            messages_intro?: components["schemas"]["MessagesIntroPayload"];
            our_story?: components["schemas"]["OurStoryPayload"];
            rsvp?: components["schemas"]["RSVPPayload"];
            /**
             * @description Always present in responses; ignored in the section-update request body (the path decides).
             * @enum {string}
             */
            slug?: "hero" | "our_story" | "big_day" | "rsvp" | "getting_there" | "stay" | "gifts_intro" | "dress_code" | "good_practices" | "messages_intro";
            stay?: components["schemas"]["StayPayload"];
        };
        SectionsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SectionsOutputBody.json
             */
            readonly $schema?: string;
            sections: components["schemas"]["Section"][] | null;
        };
        StayPayload: {
            /** @description Neighborhoods worth searching on Airbnb. */
            airbnb_areas?: string[] | null;
            /** @description Rich text as Markdown. */
            body?: string;
            /** @description Public CDN image URLs. */
            images?: string[] | null;
            lodgings?: components["schemas"]["Lodging"][] | null;
            /** @description Section heading shown on the site. */
            title: string;
        };
        SuggestOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SuggestOutputBody.json
             */
            readonly $schema?: string;
            /** @description Up to 8 full names. Pick one and confirm it via POST /guests/lookup. */
            suggestions: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "admin-list-contributions": {
        parameters: {
            query?: {
                /** @description Filter by status; omit for all. */
                status?: "declared" | "confirmed" | "cancelled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-moderate-contribution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contribution_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateContributionInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGiftsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-create-gift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftParamsBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-gift": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftParamsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-gift": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGiftOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-guest-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-export-guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-import-guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-upload-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description Optional accessibility text. */
                    alt: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-delete-media": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-messages": {
        parameters: {
            query?: {
                /** @description Filter by status; omit for all. */
                status?: "pending" | "approved" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-moderate-message": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateMessageInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-list-sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-update-section": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "hero" | "our_story" | "big_day" | "rsvp" | "getting_there" | "stay" | "gifts_intro" | "dress_code" | "good_practices" | "messages_intro";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Section"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "declare-contribution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContributionInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "preview-gift-pix": {
        parameters: {
            query?: {
                /** @description Amount in centavos. Optional for quota gifts (defaults to one quota); required for free-amount gifts. */
                amount_centavos?: number;
            };
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PixOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "lookup-guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "suggest-guest-names": {
        parameters: {
            query: {
                /** @description Beginning of the guest's name; matching ignores case and accents. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "submit-rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RSVPInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageCreatedOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
